"""create tickets and batch_jobs

Revision ID: f565b4d326bc
Revises: 
Create Date: 2026-08-31 22:01:30.626982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f565b4d326bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='ck_batch_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_batch_jobs_status', 'batch_jobs', ['status'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('predicted_queue', sa.String(length=64), nullable=False),
    sa.Column('predicted_sentiment', sa.String(length=16), nullable=False),
    sa.Column('routed_team', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("predicted_sentiment IN ('Negative', 'Neutral', 'Positive')", name='ck_tickets_sentiment'),
    sa.CheckConstraint("priority IN ('normal', 'urgent')", name='ck_tickets_priority'),
    sa.CheckConstraint("source IN ('slack', 'email', 'csv')", name='ck_tickets_source'),
    sa.CheckConstraint("status IN ('open', 'in_progress', 'resolved')", name='ck_tickets_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_tickets_created_at', 'tickets', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_tickets_predicted_queue', 'tickets', ['predicted_queue'], unique=False)
    op.create_index('ix_tickets_predicted_sentiment', 'tickets', ['predicted_sentiment'], unique=False)
    op.create_index('ix_tickets_queue_status', 'tickets', ['predicted_queue', 'status'], unique=False)
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.drop_index('ix_tickets_queue_status', table_name='tickets')
    op.drop_index('ix_tickets_predicted_sentiment', table_name='tickets')
    op.drop_index('ix_tickets_predicted_queue', table_name='tickets')
    op.drop_index('ix_tickets_created_at', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_batch_jobs_status', table_name='batch_jobs')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
